baseurl: '/'
permalink: pretty
title: 'Java Blog'

logo:
  mobile: "images/logo/java-svgrepo-com.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/java-blog.svg"
  desktop_height: "70px"
  desktop_width: "200px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE

highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 8
paginate_path: "/services/page:num/"